# Generated by Django 4.1.5 on 2023-06-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='images',
        ),
    ]
