# Generated by Django 4.1.5 on 2023-06-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_ad_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userpassword',
            new_name='password',
        ),
    ]
